## Numpy array and basics

In [5]:
import numpy as np

Creating list from array

In [6]:
arr1=np.array([1,2,3,4,5])
print("1D ARRAY:",arr1)

arr2=np.array([[1,2,3],[4,5,6]])
print("2D ARRAY:",arr2)


1D ARRAY: [1 2 3 4 5]
2D ARRAY: [[1 2 3]
 [4 5 6]]


#List vs numpy array

In [9]:
py_list=[1,2,3]
print("Multiplication of list",py_list*2)

np_array=np.array([1,2,3])
print("Multiplication of numpy array",np_array*2) # 2 is scalar


import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("\n List time:",time.time()-start)

start=time.time()
np_arry=np.arange(100000)*2
print("\n numpy time:",time.time()-start)


Multiplication of list [1, 2, 3, 1, 2, 3]
Multiplication of numpy array [2 4 6]

 List time: 0.004704952239990234

 numpy time: 0.0007886886596679688


creating array from scratch

In [ ]:
zeros=np.zeros((3,4))
print(zeros)

ones=np.ones((3,4))
print(ones)

full=np.full((2,2),6)
print(full)

random=np.random.randint((2,3))
print(random)

seq=np.arange(0,11,2)
print(seq)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6]
 [6 6]]
[0 2]
[0 2 4 6 8]


## vector , matrice and tensor


In [34]:
vector=np.array([1,2,3])
print(vector)

matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# properties of array

In [38]:
arr=np.array([[1,2,3],[4,5,True]])
print("Shape",arr.shape)
print("Dimensions",arr.ndim)
print("Size",arr.size)
print("Dtype",arr.dtype)

Shape (2, 3)
Dimensions 2
Size 6
Dtype int64


### Array Reshaping

In [50]:
arr=np.arange(12)
print(arr)

reshaped=arr.reshape((2,6))
print(reshaped)

flattened=reshaped.flatten()
print(flattened)

raveled=reshaped.ravel()
print(raveled)

transpose=reshaped.T
print(transpose)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
